databases:
  - name: ksp-simple-curd
    databaseName: simpledb
    user: ksp

services:
  - type: web
    name: poetry-render-demo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn poetry-render-demo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poetry-render-demo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4