databases:
  - name: poetry-render-crud
    databaseName: poetry-render-crud
    user: poetry-render-crud

services:
  - type: web
    name: poetry-render-crud
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn poetry-render-crud.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poetry-render-crud
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4